name: Build and Deploy Docker Image
# Disparar el workflow en push a la rama main
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del c√≥digo
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3 

      # Paso 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 3: Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 4: Construir y publicar la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/insightflow-workspace-service:latest
            ${{ secrets.DOCKER_USERNAME }}/insightflow-workspace-service:${{ github.sha }}
